### ISSUE TITLE
4th token

### ISSUE THREAD

**Issue by ShakeJunt01** [jacob-grahn/platform-racing-2-server#419] opened 2018-04-19 02:02 UTC
So I heard f@h was fixed but it sadly seems like I didn't receive my 4th token anyway. 

![image](https://user-images.githubusercontent.com/37563497/38967212-0750397a-4354-11e8-8573-cfae425cc5d7.png)
![image](https://user-images.githubusercontent.com/37563497/38967235-1c64ef36-4354-11e8-932d-89b4b3519c65.png)

**Comment by EternalUF** [comment] 2018-04-19 14:52
I got my 5th :shrug:

**Comment by Stxtics** [comment] 2018-04-19 14:54
How long ago did you get 1 mil points, you might just need to wait longer.

**Comment by ShakeJunt01** [comment] 2018-04-19 16:17
@Stxtics a month

**Comment by jacob-grahn** [comment] 2018-04-20 13:15
The prizes can't be awarded when an account is logged in. The prize script has been running once a day, but if you happen to always be online at that time of day then you're out of luck. I changed it to run once per hour, so it should have a better shot of finding accounts when they're offline.

**Comment by Stxtics** [comment] 2018-04-21 16:02
My account Stxtics got 1 million points today and I stayed offline for a bit over 2 hours and received my 4th. @ShakeJunt01 said he folded when f@h rewards were broken so I think the game thinks he has his  4th token when actually he doesn't.

**Comment by ShakeJunt01** [comment] 2018-04-21 16:53
Yeah I haven't really logged in on my account for more than a day and I still have nothing

**Comment by bls1999** [comment] 2018-04-21 22:25
@jacob-grahn I'm going to modify my pull to check continuity between the rank_tokens and folding_at_home tables.  I figure the issue might be due to a prize being marked as awarded in the folding_at_home table but not actually awarded in the rank_tokens or pr2 tables.

**Comment by Rebuked** [comment] 2018-04-22 01:12
Hey Jacob, XeNo Here. I have also not recieved my 5Th token on Chaurus Reaper.
![ch](https://user-images.githubusercontent.com/38596762/39090272-f6b82436-45da-11e8-81be-e20caadf676a.png)
![chh](https://user-images.githubusercontent.com/38596762/39090273-02224eb4-45db-11e8-9b67-e4e9d7ba2441.png)

**Comment by EternalUF** [comment] 2018-04-22 03:38
As you can see the results are pretty mixed.. 🤷‍♂️ @jacob-grahn

**Comment by Stxtics** [comment] 2018-04-22 10:03
Ok I think I know the reason, like I said in a previous post my account Stxtics got 4th token in just over 2 hours. At 5am BST (probably a bit before) my account Doomster Jr got 10 million points, I just logged on it at 11 am BST so 6 hours later and I do not have my 5th token. See the pattern? Eternal also got 5th recently. He doesn't have a space in his name, neither does Stxtics. $shake Junt, Chaurus Reaper and Doomster Jr all have spaces in their name and they did not get their rewards. Originally I thought it was that it thought they had already received their prizes but not I believe the issue is to do with spaces in account names.

**Comment by bls1999** [comment] 2018-04-22 10:05
@Stxtics I really hope this is not as simple as the underscore replacement being faulty. I've been completely rewriting `fah_award_prize_fns.php` for 6 hours.

**Comment by Stxtics** [comment] 2018-04-22 10:09
Yeah I hope it isn't too long but it seems like this could be why, my account Suppression will be getting folded soon once Stxtics gets 5th so if Stxtics receives the 5th token and Suppression gets a PM about the 4th token which it probably will due to the name change (it already has 4th) then this must be the reason fah is faulty.

**Comment by bls1999** [comment] 2018-04-22 10:11
@Stxtics I just looked at the blame for `fah_award_prize.php` and it looks like that line hasn't been edited in the entire time the http_server has been on github.

**Comment by bls1999** [comment] 2018-04-22 11:30
Update: I guess it's been broken for the whole time it's been on GitHub.  I just fixed it in #420.

**Comment by Rebuked** [comment] 2018-04-22 11:45
@bls1999 It's fixed?

**Comment by bls1999** [comment] 2018-04-22 11:53
@Rebuked when @jacob-grahn merges #420, it will be fixed.

**Comment by Rebuked** [comment] 2018-04-22 14:33
@bls1999 Alright :)

**Closed** 2018-04-27 14:54 UTC
